## Shell Script collection
[".local/scripts/papanito"]
    type = "git-repo"
    url = "git@gitlab.com:papanito/shell-scripts.git"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
[".local/scripts/wondershaper"]
    type = "git-repo"
    url = "git@github.com:magnific0/wondershaper.git"
    exact = true
    refreshPeriod = "168h"    
[".local/share/nautilus/scripts/"]
    type = "git-repo"
    url = "git@github.com:papanito/nautilus-scripts.git"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
[".local/scripts/DevOps-Bash-tools"]
    type = "git-repo"
    url = "git@github.com:HariSekhon/DevOps-Bash-tools.git"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
[".local/scripts/backup_docker_scripts"]
    type = "git-repo"
    url = "git@github.com:alaub81/backup_docker_scripts.git"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
[".local/scripts/bash-snippets"]
    type = "git-repo"
     url = "git@github.com:alexanderepstein/Bash-Snippets.git"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
## Tools
# [".emacs.d"]
#     type = "git-repo"
#     url = "https://github.com/doomemacs/doomemacs"
#     exact = true
#     stripComponents = 2
#     refreshPeriod = "168h"
[".config/cheat/cheatsheets/personal"]
    type = "git-repo"
    url = "git@github.com:cheat/cheatsheets.git"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
[".local/share/navi/cheats/papanito__cheats"]
    type = "git-repo"
    url = "git@github.com:papanito/cheats.git"
    exact = true
    refreshPeriod = "168h"
## git-hooks
[ ".config/git/hooks"]
    type = "git-repo"
    url = "git@gitlab.com:papanito/git-hooks.git"
    exact = true
    refreshPeriod = "168h"

